/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSponsorsRouteImport } from './routes/_authenticated/sponsors'
import { Route as AuthenticatedSynthesizeRouteImport } from './routes/_authenticated/synthesize'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications.$applicationId'
import { Route as ApiPublicAgentTickRouteImport } from './routes/api/public/agent-tick'
import { Route as ApiPublicGmailPushRouteImport } from './routes/api/public/gmail-push'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as OauthGmailReturnRouteImport } from './routes/oauth/gmail/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSponsorsRoute = AuthenticatedSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSynthesizeRoute = AuthenticatedSynthesizeRouteImport.update({
  id: '/synthesize',
  path: '/synthesize',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const ApiPublicAgentTickRoute = ApiPublicAgentTickRouteImport.update({
  id: '/api/public/agent-tick',
  path: '/api/public/agent-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGmailPushRoute = ApiPublicGmailPushRouteImport.update({
  id: '/api/public/gmail-push',
  path: '/api/public/gmail-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGmailReturnRoute = OauthGmailReturnRouteImport.update({
  id: '/oauth/gmail/return',
  path: '/oauth/gmail/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/connections': typeof AuthenticatedConnectionsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sponsors': typeof AuthenticatedSponsorsRoute
  '/synthesize': typeof AuthenticatedSynthesizeRoute
  '/today': typeof AuthenticatedTodayRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
  '/api/public/gmail-push': typeof ApiPublicGmailPushRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/oauth/gmail/return': typeof OauthGmailReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/connections': typeof AuthenticatedConnectionsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sponsors': typeof AuthenticatedSponsorsRoute
  '/synthesize': typeof AuthenticatedSynthesizeRoute
  '/today': typeof AuthenticatedTodayRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
  '/api/public/gmail-push': typeof ApiPublicGmailPushRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/oauth/gmail/return': typeof OauthGmailReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sponsors': typeof AuthenticatedSponsorsRoute
  '/_authenticated/synthesize': typeof AuthenticatedSynthesizeRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
  '/api/public/gmail-push': typeof ApiPublicGmailPushRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/oauth/gmail/return': typeof OauthGmailReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/connections'
    | '/portal'
    | '/radar'
    | '/resume'
    | '/saved'
    | '/settings'
    | '/sponsors'
    | '/synthesize'
    | '/today'
    | '/vault'
    | '/applications/$applicationId'
    | '/api/public/agent-tick'
    | '/api/public/gmail-push'
    | '/api/public/health'
    | '/oauth/gmail/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/connections'
    | '/portal'
    | '/radar'
    | '/resume'
    | '/saved'
    | '/settings'
    | '/sponsors'
    | '/synthesize'
    | '/today'
    | '/vault'
    | '/applications/$applicationId'
    | '/api/public/agent-tick'
    | '/api/public/gmail-push'
    | '/api/public/health'
    | '/oauth/gmail/return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/connections'
    | '/_authenticated/portal'
    | '/_authenticated/radar'
    | '/_authenticated/resume'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/_authenticated/sponsors'
    | '/_authenticated/synthesize'
    | '/_authenticated/today'
    | '/_authenticated/vault'
    | '/_authenticated/applications/$applicationId'
    | '/api/public/agent-tick'
    | '/api/public/gmail-push'
    | '/api/public/health'
    | '/oauth/gmail/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAgentTickRoute: typeof ApiPublicAgentTickRoute
  ApiPublicGmailPushRoute: typeof ApiPublicGmailPushRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  OauthGmailReturnRoute: typeof OauthGmailReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sponsors': {
      id: '/_authenticated/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof AuthenticatedSponsorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/synthesize': {
      id: '/_authenticated/synthesize'
      path: '/synthesize'
      fullPath: '/synthesize'
      preLoaderRoute: typeof AuthenticatedSynthesizeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/api/public/agent-tick': {
      id: '/api/public/agent-tick'
      path: '/api/public/agent-tick'
      fullPath: '/api/public/agent-tick'
      preLoaderRoute: typeof ApiPublicAgentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gmail-push': {
      id: '/api/public/gmail-push'
      path: '/api/public/gmail-push'
      fullPath: '/api/public/gmail-push'
      preLoaderRoute: typeof ApiPublicGmailPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/gmail/return': {
      id: '/oauth/gmail/return'
      path: '/oauth/gmail/return'
      fullPath: '/oauth/gmail/return'
      preLoaderRoute: typeof OauthGmailReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsApplicationIdRoute:
      AuthenticatedApplicationsApplicationIdRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSponsorsRoute: typeof AuthenticatedSponsorsRoute
  AuthenticatedSynthesizeRoute: typeof AuthenticatedSynthesizeRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSponsorsRoute: AuthenticatedSponsorsRoute,
  AuthenticatedSynthesizeRoute: AuthenticatedSynthesizeRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAgentTickRoute: ApiPublicAgentTickRoute,
  ApiPublicGmailPushRoute: ApiPublicGmailPushRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  OauthGmailReturnRoute: OauthGmailReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
